package com.acn.ebx.path;

import com.orchestranetworks.schema.*;
/**
 * Generated by EBX5 5.8.1 fix I [1067:0019], at  2019/11/08 16:29:50 [IST].
 * WARNING: Any manual changes to this class may be overwritten by generation process.
 * DO NOT MODIFY THIS CLASS.
 * 
 * This interface defines constants related to schema [Module: deep-blue, path: /WEB-INF/ebx/schemas/DeepBlueModel.xsd].
 * 
 * Root paths in this interface: 
 * 	'/root'   relativeToRoot: false
 * 
 */
public interface Paths
{
	// ===============================================
	// Constants for nodes under '/root'.
	// Prefix:  ''.
	// Statistics:
	//		390 path constants.
	//		239 leaf nodes.
	public static final Path _Root = Path.parse("/root");

	// Table type path
	public final class _CustomerSegment
	{
		private static final Path _CustomerSegment = _Root.add("CustomerSegment");
		public static Path getPathInSchema()
		{
			return _CustomerSegment;
		}
		public static final Path _CustomerSegmentId = Path.parse("./customerSegmentId");
		public static final Path _CustomerId = Path.parse("./customerId");
		public static final Path _Brand = Path.parse("./brand");
		public static final Path _Tier = Path.parse("./tier");
		public static final Path _InteractionResponse = Path.parse("./interactionResponse");
		public static final Path _KeyMessage = Path.parse("./keyMessage");
		public static final Path _KeyMessageCategory = Path.parse("./keyMessageCategory");
		public static final Path _PortfolioTier = Path.parse("./portfolioTier");
		public static final Path _Segmentation = Path.parse("./segmentation");
		public static final Path _CustomerCountry = Path.parse("./customerCountry");
	} 

	// Table type path
	public final class _Address
	{
		private static final Path _Address = _Root.add("Address");
		public static Path getPathInSchema()
		{
			return _Address;
		}
		public static final Path _AddressId = Path.parse("./addressId");
		public static final Path _CustomerId = Path.parse("./customerId");
		public static final Path _IsPrimary = Path.parse("./isPrimary");
		public static final Path _AddressType = Path.parse("./addressType");
		public static final Path _AddressLine1 = Path.parse("./addressLine1");
		public static final Path _AddressLine2 = Path.parse("./addressLine2");
		public static final Path _AddressLine3 = Path.parse("./addressLine3");
		public static final Path _City = Path.parse("./city");
		public static final Path _State = Path.parse("./state");
		public static final Path _Province = Path.parse("./province");
		public static final Path _Zip = Path.parse("./zip");
		public static final Path _Country = Path.parse("./country");
		public static final Path _Brick = Path.parse("./brick");
		public static final Path _Microbrick = Path.parse("./microbrick");
		public static final Path _Latitude = Path.parse("./latitude");
		public static final Path _Longitude = Path.parse("./longitude");
		public static final Path _Height = Path.parse("./height");
		public static final Path _GeographicCoordinates = Path.parse("./geographicCoordinates");
		public static final Path _EffectiveDate = Path.parse("./effectiveDate");
		public static final Path _AddressStatus = Path.parse("./addressStatus");
		public static final Path _AddressVerificationStatus = Path.parse("./addressVerificationStatus");
		public static final Path _Communication = Path.parse("./communication");
		public static final Path _CustomerCountry = Path.parse("./customerCountry");
		public static final Path _System = Path.parse("./system");
		public static final Path _SystemKey = Path.parse("./systemKey");
		public static final Path _UpdatedInMDM = Path.parse("./updatedInMDM");
	} 

	// Table type path
	public final class _RemoteKeys
	{
		private static final Path _RemoteKeys = _Root.add("RemoteKeys");
		public static Path getPathInSchema()
		{
			return _RemoteKeys;
		}
		public static final Path _CustomerId = Path.parse("./customerId");
		public static final Path _SourceName = Path.parse("./sourceName");
		public static final Path _SourceCode = Path.parse("./sourceCode");
		public static final Path _EffectiveDate = Path.parse("./effectiveDate");
		public static final Path _ExpirationDate = Path.parse("./expirationDate");
		public static final Path _SynchronizationStatus = Path.parse("./synchronizationStatus");
		public static final Path _LastSynchronizedDate = Path.parse("./lastSynchronizedDate");
		public static final Path _LastSynchronizedStatusUpdatedDate = Path.parse("./lastSynchronizedStatusUpdatedDate");
		public static final Path _Comment = Path.parse("./comment");
		public static final Path _CustomerCountry = Path.parse("./customerCountry");
	} 

	// Table type path
	public final class _Customer
	{
		private static final Path _Customer = _Root.add("Customer");
		public static Path getPathInSchema()
		{
			return _Customer;
		}
		public static final Path _CustomerId = Path.parse("./customerId");
		public static final Path _Type = Path.parse("./type");
		public static final Path _Name = Path.parse("./name");
		public static final Path _Status = Path.parse("./status");
		public static final Path _StatusReason = Path.parse("./statusReason");
		public static final Path _StatusComment = Path.parse("./statusComment");
		public static final Path _ValidationStatus = Path.parse("./validationStatus");
		public static final Path _Country = Path.parse("./country");
		public static final Path _RecordTypeId = Path.parse("./recordTypeId");
		public static final Path _RecordTypeValue = Path.parse("./recordTypeValue");
		public static final Path _CustomerCountry = Path.parse("./customerCountry");
		public static final Path _Hco = Path.parse("./hco");
		public static final Path _Hcp = Path.parse("./hcp");
		public static final Path _Addresses = Path.parse("./addresses");
		public static final Path _Communication = Path.parse("./communication");
		public static final Path _Education = Path.parse("./education");
		public static final Path _Specialty = Path.parse("./specialty");
		public static final Path _AdditionalQualification = Path.parse("./additionalQualification");
		public static final Path _CustomerParent = Path.parse("./customerParent");
		public static final Path _CustomerChildren = Path.parse("./customerChildren");
		public static final Path _Consent = Path.parse("./consent");
		public static final Path _CustomerSegment = Path.parse("./customerSegment");
		public static final Path _Credentials = Path.parse("./credentials");
		public static final Path _CrossReferences = Path.parse("./crossReferences");
		public static final Path _Tracking = Path.parse("./tracking");
	} 

	// Table type path
	public final class _ConsentDefintion
	{
		private static final Path _ConsentDefintion = _Root.add("ConsentDefintion");
		public static Path getPathInSchema()
		{
			return _ConsentDefintion;
		}
		public static final Path _ConsentDefintionId = Path.parse("./ConsentDefintionId");
		public static final Path _ConsentName = Path.parse("./consentName");
		public static final Path _Purpose = Path.parse("./purpose");
		public static final Path _Characteristics = Path.parse("./characteristics");
		public static final Path _SourceLocation = Path.parse("./sourceLocation");
		public static final Path _CollectedBy = Path.parse("./collectedBy");
		public static final Path _Channel = Path.parse("./channel");
		public static final Path _CustomerCountry = Path.parse("./customerCountry");
	} 

	// Table type path
	public final class _HealthCareProfessional
	{
		private static final Path _HealthCareProfessional = _Root.add("HealthCareProfessional");
		public static Path getPathInSchema()
		{
			return _HealthCareProfessional;
		}
		public static final Path _HcpId = Path.parse("./hcpId");
		public static final Path _CustomerId = Path.parse("./customerId");
		public static final Path _Salutation = Path.parse("./salutation");
		public static final Path _FirstName = Path.parse("./firstName");
		public static final Path _FirstName2 = Path.parse("./firstName2");
		public static final Path _MiddleName = Path.parse("./middleName");
		public static final Path _MiddleName2 = Path.parse("./middleName2");
		public static final Path _LastName = Path.parse("./lastName");
		public static final Path _LastName2 = Path.parse("./lastName2");
		public static final Path _FullName = Path.parse("./fullName");
		public static final Path _Suffix = Path.parse("./suffix");
		public static final Path _Title = Path.parse("./title");
		public static final Path _DateOfBirth = Path.parse("./dateOfBirth");
		public static final Path _Gender = Path.parse("./gender");
		public static final Path _Language = Path.parse("./language");
		public static final Path _IsPortalUser = Path.parse("./isPortalUser");
		public static final Path _CustomerType = Path.parse("./customerType");
		public static final Path _HcpType = Path.parse("./hcpType");
		public static final Path _SubType = Path.parse("./subType");
		public static final Path _KolIndicator = Path.parse("./kolIndicator");
		public static final Path _PrimaryAddressLine1 = Path.parse("./primaryAddressLine1");
		public static final Path _PrimaryAddressLine2 = Path.parse("./primaryAddressLine2");
		public static final Path _PrimaryAddressLine3 = Path.parse("./primaryAddressLine3");
		public static final Path _PrimaryZip = Path.parse("./primaryZip");
		public static final Path _PrimaryCity = Path.parse("./primaryCity");
		public static final Path _PrimaryCountry = Path.parse("./primaryCountry");
		public static final Path _CustomerCountry = Path.parse("./customerCountry");
		public static final Path _System = Path.parse("./system");
		public static final Path _SystemKey = Path.parse("./systemKey");
		public static final Path _UpdatedInMDM = Path.parse("./updatedInMDM");
	} 

	// Table type path
	public final class _AdditionalQualification
	{
		private static final Path _AdditionalQualification = _Root.add("AdditionalQualification");
		public static Path getPathInSchema()
		{
			return _AdditionalQualification;
		}
		public static final Path _AdditionalQualificationId = Path.parse("./additionalQualificationId");
		public static final Path _CustomerID = Path.parse("./customerID");
		public static final Path _Type = Path.parse("./type");
		public static final Path _Value = Path.parse("./value");
		public static final Path _Status = Path.parse("./status");
		public static final Path _CustomerCountry = Path.parse("./customerCountry");
		public static final Path _System = Path.parse("./system");
		public static final Path _SystemKey = Path.parse("./systemKey");
		public static final Path _UpdatedInMDM = Path.parse("./updatedInMDM");
	} 

	// Table type path
	public final class _Specialty
	{
		private static final Path _Specialty = _Root.add("Specialty");
		public static Path getPathInSchema()
		{
			return _Specialty;
		}
		public static final Path _SpecialtyId = Path.parse("./specialtyId");
		public static final Path _CustomerId = Path.parse("./customerId");
		public static final Path _Type = Path.parse("./type");
		public static final Path _Value = Path.parse("./value");
		public static final Path _Status = Path.parse("./status");
		public static final Path _CustomerCountry = Path.parse("./customerCountry");
		public static final Path _System = Path.parse("./system");
		public static final Path _SystemKey = Path.parse("./systemKey");
		public static final Path _UpdatedInMDM = Path.parse("./updatedInMDM");
	} 

	// Table type path
	public final class _Education
	{
		private static final Path _Education = _Root.add("Education");
		public static Path getPathInSchema()
		{
			return _Education;
		}
		public static final Path _EducationId = Path.parse("./educationId");
		public static final Path _CustomerId = Path.parse("./customerId");
		public static final Path _Degree = Path.parse("./degree");
		public static final Path _GraduationYear = Path.parse("./graduationYear");
		public static final Path _Institution = Path.parse("./institution");
		public static final Path _CustomerCountry = Path.parse("./customerCountry");
		public static final Path _System = Path.parse("./system");
		public static final Path _SystemKey = Path.parse("./systemKey");
		public static final Path _UpdatedInMDM = Path.parse("./updatedInMDM");
	} 

	// Table type path
	public final class _Consent
	{
		private static final Path _Consent = _Root.add("Consent");
		public static Path getPathInSchema()
		{
			return _Consent;
		}
		public static final Path _ConsentId = Path.parse("./consentId");
		public static final Path _CustomerId = Path.parse("./customerId");
		public static final Path _Type = Path.parse("./type");
		public static final Path _Value = Path.parse("./value");
		public static final Path _Status = Path.parse("./status");
		public static final Path _Country = Path.parse("./country");
		public static final Path _IsGlobal = Path.parse("./isGlobal");
		public static final Path _DateOfConsent = Path.parse("./dateOfConsent");
		public static final Path _IssueExpirationDate = Path.parse("./issueExpirationDate");
		public static final Path _Brand = Path.parse("./brand");
		public static final Path _ProductId = Path.parse("./productId");
		public static final Path _ConsentDefintion = Path.parse("./ConsentDefintion");
		public static final Path _CustomerCountry = Path.parse("./customerCountry");
	} 

	// Table type path
	public final class _HealthCareOrganization
	{
		private static final Path _HealthCareOrganization = _Root.add("HealthCareOrganization");
		public static Path getPathInSchema()
		{
			return _HealthCareOrganization;
		}
		public static final Path _HcoId = Path.parse("./hcoId");
		public static final Path _CustomerId = Path.parse("./customerId");
		public static final Path _Name = Path.parse("./name");
		public static final Path _Alias = Path.parse("./alias");
		public static final Path _Department = Path.parse("./department");
		public static final Path _NumberOfBeds = Path.parse("./numberOfBeds");
		public static final Path _TheurapticArea = Path.parse("./theurapticArea");
		public static final Path _HcoLegalEntity = Path.parse("./hcoLegalEntity");
		public static final Path _RequiredCertifications = Path.parse("./requiredCertifications");
		public static final Path _Groupings = Path.parse("./groupings");
		public static final Path _CustomerType = Path.parse("./customerType");
		public static final Path _HcoType = Path.parse("./hcoType");
		public static final Path _HcoSubType = Path.parse("./hcoSubType");
		public static final Path _PrimaryAddressLine1 = Path.parse("./primaryAddressLine1");
		public static final Path _PrimaryAddressLine2 = Path.parse("./primaryAddressLine2");
		public static final Path _PrimaryAddressLine3 = Path.parse("./primaryAddressLine3");
		public static final Path _PrimaryZip = Path.parse("./primaryZip");
		public static final Path _PrimaryCity = Path.parse("./primaryCity");
		public static final Path _PrimaryCountry = Path.parse("./primaryCountry");
		public static final Path _CustomerCountry = Path.parse("./customerCountry");
		public static final Path _System = Path.parse("./system");
		public static final Path _SystemKey = Path.parse("./systemKey");
		public static final Path _UpdatedInMDM = Path.parse("./updatedInMDM");
	} 

	// Table type path
	public final class _CustomerDCR
	{
		private static final Path _CustomerDCR = _Root.add("CustomerDCR");
		public static Path getPathInSchema()
		{
			return _CustomerDCR;
		}
		public static final Path _Id = Path.parse("./Id");
		public static final Path _DcrType = Path.parse("./dcrType");
		public static final Path _CountryRefData = Path.parse("./countryRefData");
		public static final Path _RequesterName = Path.parse("./requesterName");
		public static final Path _NovartisComment = Path.parse("./novartisComment");
		public static final Path _CreationDate = Path.parse("./creationDate");
		public static final Path _LastUpdateDate = Path.parse("./lastUpdateDate");
		public static final Path _CrmCustomerId = Path.parse("./crmCustomerId");
		public static final Path _CustomerId = Path.parse("./customerId");
		public static final Path _Status = Path.parse("./status");
		public static final Path _AddressNormalization = Path.parse("./addressNormalization");
		public static final Path _SentToThirdParty = Path.parse("./sentToThirdParty");
		public static final Path _CustomerCountry = Path.parse("./customerCountry");
		public static final Path _OkRequestId = Path.parse("./okRequestId");
		public static final Path _RequestType = Path.parse("./requestType");
		public static final Path _CountryISOCode2 = Path.parse("./countryISOCode2");
		public static final Path _ResponseStatus = Path.parse("./responseStatus");
		public static final Path _LastStatusUpdateDate = Path.parse("./lastStatusUpdateDate");
		public static final Path _OneKeyComment = Path.parse("./oneKeyComment");
		public static final Path _IndividualEidSource = Path.parse("./individualEidSource");
		public static final Path _IndividualEidValidated = Path.parse("./individualEidValidated");
		public static final Path _WorkplaceEidSource = Path.parse("./workplaceEidSource");
		public static final Path _WorkplaceEidValidated = Path.parse("./workplaceEidValidated");
		public static final Path _ActivityEidSource = Path.parse("./activityEidSource");
		public static final Path _ActivityEidValidated = Path.parse("./activityEidValidated");
		public static final Path _AddressEidSource = Path.parse("./addressEidSource");
		public static final Path _AddressEidValidated = Path.parse("./addressEidValidated");
	} 

	// Table type path
	public final class _Credentials
	{
		private static final Path _Credentials = _Root.add("Credentials");
		public static Path getPathInSchema()
		{
			return _Credentials;
		}
		public static final Path _CredentialId = Path.parse("./credentialId");
		public static final Path _CustomerId = Path.parse("./customerId");
		public static final Path _Type = Path.parse("./type");
		public static final Path _Value = Path.parse("./value");
		public static final Path _Status = Path.parse("./status");
		public static final Path _IssueState = Path.parse("./issueState");
		public static final Path _IssueCountry = Path.parse("./issueCountry");
		public static final Path _IssueDate = Path.parse("./issueDate");
		public static final Path _IssueExpirationDate = Path.parse("./issueExpirationDate");
		public static final Path _CustomerCountry = Path.parse("./customerCountry");
		public static final Path _System = Path.parse("./system");
		public static final Path _SystemKey = Path.parse("./systemKey");
		public static final Path _UpdatedInMDM = Path.parse("./updatedInMDM");
	} 

	// Table type path
	public final class _Communication
	{
		private static final Path _Communication = _Root.add("Communication");
		public static Path getPathInSchema()
		{
			return _Communication;
		}
		public static final Path _CommunicationId = Path.parse("./communicationId");
		public static final Path _CustomerId = Path.parse("./customerId");
		public static final Path _CommunicationType = Path.parse("./communicationType");
		public static final Path _Type = Path.parse("./type");
		public static final Path _Value = Path.parse("./value");
		public static final Path _Status = Path.parse("./status");
		public static final Path _IsPrimary = Path.parse("./isPrimary");
		public static final Path _Address = Path.parse("./address");
		public static final Path _CustomerCountry = Path.parse("./customerCountry");
		public static final Path _System = Path.parse("./system");
		public static final Path _SystemKey = Path.parse("./systemKey");
		public static final Path _UpdatedInMDM = Path.parse("./updatedInMDM");
	} 

	// Table type path
	public final class _Affiliation
	{
		private static final Path _Affiliation = _Root.add("Affiliation");
		public static Path getPathInSchema()
		{
			return _Affiliation;
		}
		public static final Path _AffiliationId = Path.parse("./affiliationId");
		public static final Path _ParentId = Path.parse("./parentId");
		public static final Path _ChildId = Path.parse("./childId");
		public static final Path _AffiliationType = Path.parse("./affiliationType");
		public static final Path _LinkTYpe = Path.parse("./linkTYpe");
		public static final Path _StartDate = Path.parse("./startDate");
		public static final Path _EndDate = Path.parse("./endDate");
		public static final Path _IsPrimary = Path.parse("./isPrimary");
		public static final Path _Nanobrick = Path.parse("./nanobrick");
		public static final Path _Role = Path.parse("./role");
		public static final Path _CustomerCountry = Path.parse("./customerCountry");
		public static final Path _System = Path.parse("./system");
		public static final Path _ParentSystemKey = Path.parse("./parentSystemKey");
		public static final Path _ChildSystemKey = Path.parse("./childSystemKey");
		public static final Path _UpdatedInMDM = Path.parse("./updatedInMDM");
	} 
	// ===============================================

}
